<?xml version="1.0" encoding="utf-8"?><Database Name="DoAnBaoMat" Class="dbTikTokFakeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ACERASPIRE7\SQLEXPRESS;Initial Catalog=DoAnBaoMat;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DoAnBaoMatConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FacebookAcount" Member="FacebookAcounts">
    <Type Name="FacebookAcount">
      <Column Name="stt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SDTorEmail" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Gmail" Member="Gmails">
    <Type Name="Gmail">
      <Column Name="stt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Gmail" Member="Gmail1" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Icloud" Member="Iclouds">
    <Type Name="Icloud">
      <Column Name="stt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Icloud" Member="Icloud1" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.KaKaoAccount" Member="KaKaoAccounts">
    <Type Name="KaKaoAccount">
      <Column Name="stt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDorEmailorPhone" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LineAccount" Member="LineAccounts">
    <Type Name="LineAccount">
      <Column Name="stt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TikTokAccount" Member="TikTokAccounts">
    <Type Name="TikTokAccount">
      <Column Name="stt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SDTorMailorTTID" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TwitterAccount" Member="TwitterAccounts">
    <Type Name="TwitterAccount">
      <Column Name="stt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="twAccount" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>